In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
import pandas as pd

df1 = pd.read_csv('../data/rawdata.csv')
df1.shape

(12374, 38)

In [7]:
df1[df1['buggy'] == True]

Unnamed: 0      X                                 commit_id  \
4              15     15  001d36c97eac77410f7dd32290d2142abfb19fa0   
6              24     24  0043044f2e8ee3de8a9995bdbf51aad77f1a3fa9   
7              29     29  0057aed72c6e92fbc7bfe27eb9a30f191eed3fd4   
12             36     36  0061c0ce4443395a258a99c70e1c1a7d0435e84e   
14             43     43  006a4e5e31a12d049c3d6308c3a2d73f57cd980f   
...           ...    ...                                       ...   
12349       26802  26802  ff7623f3c9e34a30ebff213fe19c775b1848eb2a   
12351       26804  26804  ff837025e955799e69eebcab665374436649d6f8   
12358       26814  26814  ffa04d3e83ad83a51b366f1a3579ed47328c1b43   
12359       26815  26815  ffa11a64706e898ba3ae45f84920d632b5947add   
12365       26836  26836  ffcf3431982a591041d642651f778b53e6db5735   

       author_date  bugcount  fixcount   la   ld  nf  nd  ...   rsexp   osexp  \
4       1392721937         1         0   12    6   2   2  ...  1361.0  2241.0   
6       1373357890         4         0  580  283   8   5  ...    42.0    43.0   
7       1380799475         1         0    2    2   1   1  ...   449.0   473.0   
12      1340028045         1         0  462    1   4   3  ...    45.0    46.0   
14      1374767629         1         0   15    3   2   2  ...   250.0   283.0   
...            ...       ...       ...  ...  ...  ..  ..  ...     ...     ...   
12349   1383098720         1         0  757    6  17   6  ...   395.0   395.0   
12351   1344875498         1         0  360   52  10   7  ...    22.0    94.0   
12358   1367506181         1         0   30   15   2   2  ...   739.0   743.0   
12359   1380332296         1         0   11    6   3   2  ...   135.0   194.0   
12365   1362091722         1         0  430  174  12   8  ...   562.0   575.0   

          asawr     rsawr     osawr  churn buggy    fix   bugdens  strata  
4      0.147545  0.184703  0.304041     18  True  False  0.055556       8  
6      0.060000  0.860000  0.880000    863  True  False  0.004635       6  
7      0.444785  0.460123  0.484663      4  True  False  0.250000       7  
12     0.132743  0.407080  0.415929    463  True  False  0.002160       2  
14     0.041526  0.281706  0.318743     18  True  False  0.055556       6  
...         ...       ...       ...    ...   ...    ...       ...     ...  
12349  0.005859  0.773438  0.773438    763  True  False  0.001311       7  
12351  0.371429  0.109524  0.452381    412  True  False  0.002427       2  
12358  0.019210  0.789755  0.794023     45  True  False  0.022222       5  
12359  0.250627  0.340852  0.488722     17  True  False  0.058824       7  
12365  0.342291  0.796322  0.814710    604  True  False  0.001656       5  

[2442 rows x 38 columns]

In [8]:
df1.head(20)

Unnamed: 0   X                                 commit_id  author_date  \
0            6   6  00057454f6609871c2cabf874876d26a6d0d0641   1358516662   
1            9   9  0007d255d9b20da4e5bbcdbaf5813104fbc092da   1358353428   
2           11  11  0014f2c828dae5f9481a2bac68fe90a7857b2f59   1377995125   
3           14  14  001961ed495a33cc944407888a2797f8a600e091   1367268702   
4           15  15  001d36c97eac77410f7dd32290d2142abfb19fa0   1392721937   
5           23  23  0038e3818393415fc9628aef2747136a626682ee   1341252518   
6           24  24  0043044f2e8ee3de8a9995bdbf51aad77f1a3fa9   1373357890   
7           29  29  0057aed72c6e92fbc7bfe27eb9a30f191eed3fd4   1380799475   
8           31  31  00592cfa0b90c66682be2bc31428277c35a35c48   1331588951   
9           33  33  005b9950ac84bf3ae06c24ee018f192064060428   1367521170   
10          34  34  005ef0796270cb6238dc9863b468b0f1d7026e7c   1358916201   
11          35  35  005ff1100a11c83808471ece313d0f9001f4653c   1374603627   
12          36  36  0061c0ce4443395a258a99c70e1c1a7d0435e84e   1340028045   
13          37  37  006254c5050176c9b569007f6ef7203e6067215d   1344016566   
14          43  43  006a4e5e31a12d049c3d6308c3a2d73f57cd980f   1374767629   
15          44  44  006d673d24778abe6c47e3ee7e1a19e163912440   1367348740   
16          45  45  006fea117307460544492a3548203a9ef31f34ba   1326777632   
17          46  46  0070b452f1c00817dd4a47deb57bfbe6b79c4152   1361547297   
18          48  48  00786bc554a2dfacb3c6f02fbb7e9c98f35d4262   1338278278   
19          50  50  007a1856dd8b5a781a3abe312a023344995162d6   1347632012   

    bugcount  fixcount    la   ld  nf  nd  ...   rsexp   osexp     asawr  \
0          0         0     2    2   2   2  ...   259.0   259.0  0.003472   
1          0         0     9    6   1   1  ...   276.0   277.0  0.024735   
2          0         0     7    8   2   1  ...   257.0   275.0  0.200000   
3          0         0     6    0   1   1  ...  1922.0  2506.0  0.217116   
4          1         0    12    6   2   2  ...  1361.0  2241.0  0.147545   
5          0         0    23   17   3   3  ...   536.0   536.0  0.015677   
6          4         0   580  283   8   5  ...    42.0    43.0  0.060000   
7          1         0     2    2   1   1  ...   449.0   473.0  0.444785   
8          0         0     2    2   2   1  ...   595.0   636.0  0.063436   
9          0         0     3    2   1   1  ...   836.0   847.0  0.003606   
10         0         0    39    5   3   2  ...  1210.0  1214.0  0.001645   
11         0         0   132  201   2   1  ...   673.0   673.0  0.001330   
12         1         0   462    1   4   3  ...    45.0    46.0  0.132743   
13         0         0    15    3   1   1  ...   346.0   346.0  0.707657   
14         1         0    15    3   2   2  ...   250.0   283.0  0.041526   
15         0         0    15   12   1   1  ...   477.0   477.0  0.919028   
16         0         0    14   24   3   3  ...   152.0   152.0  0.003650   
17         8         0  1793  106  26  12  ...   541.0   568.0  0.246996   
18         0         0   162  139   6   4  ...   178.0   387.0  0.161211   
19         0         0    12    6   1   1  ...   827.0   827.0  0.000398   

       rsawr     osawr  churn  buggy    fix   bugdens  strata  
0   0.902778  0.902778      4  False  False  0.000000       4  
1   0.978799  0.982332     15  False  False  0.000000       4  
2   0.573333  0.613333     15  False  False  0.000000       7  
3   0.435363  0.567580      6  False  False  0.000000       5  
4   0.184703  0.304041     18   True  False  0.055556       8  
5   0.300672  0.300672     40  False  False  0.000000       2  
6   0.860000  0.880000    863   True  False  0.004635       6  
7   0.460123  0.484663      4   True  False  0.250000       7  
8   0.525110  0.561233      4  False  False  0.000000       1  
9   0.188641  0.191120      5  False  False  0.000000       5  
10  0.332054  0.333151     44  False  False  0.000000       4  
11  0.896277  0.89627

In [ ]:
df.columns.tolist()

['Unnamed: 0',
 'X',
 'commit_id',
 'author_date',
 'bugcount',
 'fixcount',
 'la',
 'ld',
 'nf',
 'nd',
 'ns',
 'ent',
 'revd',
 'nrev',
 'rtime',
 'hcmt',
 'self',
 'ndev',
 'age',
 'nuc',
 'app',
 'aexp',
 'rexp',
 'oexp',
 'arexp',
 'rrexp',
 'orexp',
 'asexp',
 'rsexp',
 'osexp',
 'asawr',
 'rsawr',
 'osawr',
 'churn',
 'buggy',
 'fix',
 'bugdens',
 'strata']

In [9]:
df2 = pd.read_csv('../data/openstack.csv')
df2.shape

(26855, 32)

In [13]:
df2['hcmt'].head()

0    NaN
1    3.0
2    NaN
3    NaN
4    NaN
Name: hcmt, dtype: float64

In [11]:
df2.columns.tolist()

['commit_id',
 'author_date',
 'bugcount',
 'fixcount',
 'la',
 'ld',
 'nf',
 'nd',
 'ns',
 'ent',
 'revd',
 'nrev',
 'rtime',
 'tcmt',
 'hcmt',
 'self',
 'ndev',
 'age',
 'nuc',
 'app',
 'aexp',
 'rexp',
 'oexp',
 'arexp',
 'rrexp',
 'orexp',
 'asexp',
 'rsexp',
 'osexp',
 'asawr',
 'rsawr',
 'osawr']

In [19]:
original = ['ns', 'nd', 'nf', 'ent', 'la', 'ld', 'lt', 'fix', 'ndev', 'age', 'nuc', 'exp', 'rexp', 'sexp']
understood = ['aexp', 'arexp', 'asexp', 'asawr', 'rexp', 'rrexp', 'rsexp', 'rsawr', 'hcmt', 'nrev', 'app', 'rtime']
set(df2.columns.tolist()) - set(original) - set(understood)

{'author_date',
 'bugcount',
 'commit_id',
 'fixcount',
 'oexp',
 'orexp',
 'osawr',
 'osexp',
 'revd',
 'self',
 'tcmt'}

In [7]:
df3 = pd.read_csv('../data/qt.csv')
df3.shape

(32155, 32)

In [11]:
df3.columns.tolist()

['commit_id',
 'author_date',
 'bugcount',
 'fixcount',
 'la',
 'ld',
 'nf',
 'nd',
 'ns',
 'ent',
 'revd',
 'nrev',
 'rtime',
 'tcmt',
 'hcmt',
 'self',
 'ndev',
 'age',
 'nuc',
 'app',
 'aexp',
 'rexp',
 'oexp',
 'arexp',
 'rrexp',
 'orexp',
 'asexp',
 'rsexp',
 'osexp',
 'asawr',
 'rsawr',
 'osawr']

In [12]:
len(set(df2.columns.tolist()) & set(df3.columns.tolist()))

32

In [13]:
set(df1.columns.tolist()) - set(df2.columns.tolist())

{'Unnamed: 0', 'X', 'bugdens', 'buggy', 'churn', 'fix', 'strata'}

In [ ]:
y = df['buggy'].tolist()
y = [int(label) for label in y]
y[:10]

[0, 0, 0, 0, 1, 0, 1, 1, 0, 0]

In [ ]:
feature_columns = df.columns.tolist()[6:34] + df.columns.tolist()[35:]
X = df[feature_columns].to_numpy()
X = X.astype(float)
X[0]

array([2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       6.49522700e+06, 4.00000000e+00, 0.00000000e+00, 6.00000000e+00,
       1.70682000e+05, 7.00000000e+00, 2.00000000e+00, 1.20000000e+01,
       3.54000000e+02, 3.66000000e+02, 1.00000000e+01, 3.54000000e+02,
       3.64000000e+02, 0.00000000e+00, 2.59000000e+02, 2.59000000e+02,
       3.47222222e-03, 9.02777778e-01, 9.02777778e-01, 4.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 4.00000000e+00])

In [ ]:
X[56]

array([62.,  0.,  1.,  1.,  1.,  0.,  0., nan, nan, nan, nan,  0.,  0.,
        0., nan,  0., nan, nan,  0., nan, nan,  0., nan, nan,  0.,  0.,
        0., 62.,  0.,  0.,  5.])

In [ ]:
import numpy as np

nans = list(set(np.argwhere(np.isnan(X))[:, 0]))

In [ ]:
X = np.delete(X, nans, axis=0)
y = np.delete(y, nans, axis=0)

In [ ]:
print(X.shape)
print(len(y))

(12041, 31)
12041


In [ ]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0).fit(X[:11000], y[:11000])

In [ ]:
clf.predict(X[11001:11020,:])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
y[11001:11020]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1])

In [ ]:
clf.score(X[11001:], y[11001:])

0.8096153846153846