In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/My Drive/thesis/data/rawdata.csv')
df.shape

(12374, 38)

In [ ]:
df.head(20)

Unnamed: 0   X  ...   bugdens  strata
0            6   6  ...  0.000000       4
1            9   9  ...  0.000000       4
2           11  11  ...  0.000000       7
3           14  14  ...  0.000000       5
4           15  15  ...  0.055556       8
5           23  23  ...  0.000000       2
6           24  24  ...  0.004635       6
7           29  29  ...  0.250000       7
8           31  31  ...  0.000000       1
9           33  33  ...  0.000000       5
10          34  34  ...  0.000000       4
11          35  35  ...  0.000000       6
12          36  36  ...  0.002160       2
13          37  37  ...  0.000000       2
14          43  43  ...  0.055556       6
15          44  44  ...  0.000000       5
16          45  45  ...  0.000000       0
17          46  46  ...  0.004213       4
18          48  48  ...  0.000000       1
19          50  50  ...  0.000000       3

[20 rows x 38 columns]

In [ ]:
df.columns.tolist()

['Unnamed: 0',
 'X',
 'commit_id',
 'author_date',
 'bugcount',
 'fixcount',
 'la',
 'ld',
 'nf',
 'nd',
 'ns',
 'ent',
 'revd',
 'nrev',
 'rtime',
 'hcmt',
 'self',
 'ndev',
 'age',
 'nuc',
 'app',
 'aexp',
 'rexp',
 'oexp',
 'arexp',
 'rrexp',
 'orexp',
 'asexp',
 'rsexp',
 'osexp',
 'asawr',
 'rsawr',
 'osawr',
 'churn',
 'buggy',
 'fix',
 'bugdens',
 'strata']

In [ ]:
y = df['buggy'].tolist()
y = [int(label) for label in y]
y[:10]

[0, 0, 0, 0, 1, 0, 1, 1, 0, 0]

In [ ]:
feature_columns = df.columns.tolist()[6:34] + df.columns.tolist()[35:]
X = df[feature_columns].to_numpy()
X = X.astype(float)
X[0]

array([2.00000000e+00, 2.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       6.49522700e+06, 4.00000000e+00, 0.00000000e+00, 6.00000000e+00,
       1.70682000e+05, 7.00000000e+00, 2.00000000e+00, 1.20000000e+01,
       3.54000000e+02, 3.66000000e+02, 1.00000000e+01, 3.54000000e+02,
       3.64000000e+02, 0.00000000e+00, 2.59000000e+02, 2.59000000e+02,
       3.47222222e-03, 9.02777778e-01, 9.02777778e-01, 4.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 4.00000000e+00])

In [ ]:
X[56]

array([62.,  0.,  1.,  1.,  1.,  0.,  0., nan, nan, nan, nan,  0.,  0.,
        0., nan,  0., nan, nan,  0., nan, nan,  0., nan, nan,  0.,  0.,
        0., 62.,  0.,  0.,  5.])

In [ ]:
import numpy as np

nans = list(set(np.argwhere(np.isnan(X))[:, 0]))

In [ ]:
X = np.delete(X, nans, axis=0)
y = np.delete(y, nans, axis=0)

In [ ]:
print(X.shape)
print(len(y))

(12041, 31)
12041


In [ ]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0).fit(X[:11000], y[:11000])

In [ ]:
clf.predict(X[11001:11020,:])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
y[11001:11020]

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1])

In [ ]:
clf.score(X[11001:], y[11001:])

0.8096153846153846